using Entertainment_Blog.DTO.DTOs.PostDTO;
using Entertainment_Blog.Entity.Concrete;
using System;
using System.Collections.Generic;

namespace Entertainment_Blog.DTO.DTOs.UserDTO
{
    public class EditUserDTO
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Picture { get; set; }
        public DateTime DateOfBirth { get; set; }
        public GenderTypes Gender { get; set; }
        public CountryTypes Country { get; set; }
        public string Address { get; set; }
        public string Job { get; set; }
        public string About { get; set; }
        public List<PostListDTO> Posts { get; set; }
        public List<Comment> Comments { get; set; }
        public enum GenderTypes
        {
            Female,
            Male,
            Other
        }
        public enum CountryTypes
        {
            Afghanistan,
            Albania,
            Algeria,
            Andorra,
            Angola,
            Argentina,
            Armenia,
            Australia,
            Austria,
            Azerbaijan,
            Bahamas,
            Bangladesh,
            Barbados,
            Belarus,
            Belgium,
            Belize,
            Bolivia,
            Bosnia,
            Botswana,
            Brazil,
            Brunei,
            Bulgaria,
            Burma,
            Burundi,
            CaboVerde,
            Cambodia,
            Cameroon,
            Canada,
            Chad,
            Chile,
            China,
            Colombia,
            Comoros,
            Croatia,
            Cuba,
            Cyprus,
            Czechia,
            Czechoslovakia,
            Congo,
            Denmark,
            Djibouti,
            Dominica,
            DominicanRepublic,
            Ecuador,
            Egypt,
            ElSalvador,
            Eritrea,
            Estonia,
            Eswatini,
            Ethiopia,
            Fiji,
            Finland,
            France,
            Gabon,
            Gambia,
            Georgia,
            Germany,
            Ghana,
            Greece,
            Grenada,
            Guatemala,
            Guinea,
            Guyana,
            Haiti,
            Hungary,
            Iceland,
            India,
            Indonesia,
            Iran,
            Iraq,
            Ireland,
            Israel,
            Italy,
            Jamaica,
            Japan,
            Jordan,
            Kazakhstan,
            Kenya,
            Yugoslavia,
            Kiribati,
            Korea,
            Kosovo,
            Kuwait,
            Kyrgyzstan,
            Laos,
            Latvia,
            Lebanon,
            Lesotho,
            Liberia,
            Libya,
            Liechtenstein,
            Lithuania,
            Luxembourg,
            Madagascar,
            Malawi,
            Malaysia,
            Maldives,
            Mali,
            Malta,
            Mauritania,
            Mauritius,
            Mexico,
            Micronesia,
            Moldova,
            Monaco,
            Mongolia,
            Montenegro,
            Morocco,
            Mozambique,
            Namibia,
            Nauru,
            Nepal,
            Netherlands,
            NewZealand,
            Nicaragua,
            Niger,
            Nigeria,
            NorthMacedonia,
            Norway,
            Oman,
            Pakistan,
            Palau,
            Panama,
            Paraguay,
            Peru,
            Philippines,
            Poland,
            Portugal,
            Qatar,
            SouthKorea,
            Romania,
            Russia,
            Rwanda,
            Samoa,
            SaudiArabia,
            Senegal,
            Serbia,
            Seychelles,
            SierraLeone,
            Singapore,
            Slovakia,
            Slovenia,
            Somalia,
            SouthAfrica,
            SouthSudan,
            Spain,
            SriLanka,
            Sudan,
            Suriname,
            Sweden,
            Switzerland,
            Syria,
            Tajikistan,
            Tanzania,
            Texas,
            Thailand,
            Togo,
            Tonga,
            Tunisia,
            Turkey,
            Turkmenistan,
            Tuvalu,
            Uganda,
            Ukraine,
            UnitedArabEmirates,
            UnitedKingdom,
            Uruguay,
            Uzbekistan,
            Vanuatu,
            Venezuela,
            Vietnam,
            Yemen,
            Zambia,
            Zimbabwe,
        }
    }
}
